---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r clean up noaa data}
noaa = ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(tmax = as.numeric(tmax)) %>% 
  mutate(tmin = as.numeric(tmin)) %>% 
  mutate(tmax = tmax / 10) %>% 
  mutate(tmin = tmin / 10)
snowfall = sort(table(noaa$snow), decreasing = TRUE)[1:3]
```

Column {data-width=650}
-----------------------------------------------------------------------

### Snowfall

```{r snow, warning = FALSE}
snow_data = noaa %>%
  select(year, month, day, id, snow) %>%
  filter(snow > 0 & snow < 150, 
         year == "1994":"2008")
plot_ly(snow_data, y = ~snow, color = ~year, type = "box",
          colors = "Set2")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Mean Temperature

```{r temp plot, warning = FALSE}
temp = noaa %>% 
  select(id, year, month, tmax) %>% 
  filter(month == "01") %>% 
  group_by(id, year, month) %>% 
  summarise(mean = mean(tmax, na.rm = TRUE))
plot_ly(temp, x = ~year, y = ~mean, type = "bar")
```


### Max Temp vs Min Temp

```{r}
tmax = noaa %>% 
  select(id, year, month, tmax, tmin) %>% 
  filter(month == "01", year == "2008")
plot_ly(tmax, x = ~tmax, y = ~tmin, type = "scatter", mode = "markers",
          alpha = 0.5)
```

